name: Create Review App

on:
  pull_request:
    types: [opened]

env:
  ECR_REPO: fleet-ecr
  PROJECT: APP_NAME # request-bin
  SERVER_PATH: APP_SERVER_PATH # server/
  SQL_FILE: DB_SETUP_PATH # server/db/migration.sql
  BUILDER: CNBP_BUILDER # paketobuildpacks/builder:base
  DB_NAME: DATABASE_NAME # request_bin
  SUBNET_ID: DEFAULT_SUBNET_NAME # Fleet-Subnet
  SG_ID: CLUSTER_SECURITY_GROUP # Fleet-Security-3
  TASK_EXECUTION_ROLE_ARN: TASK_EXEC_ROLE_ARN
  FS_ID: EFS_CREATION_TOKEN # FleetFS
  REGION: USER_AWS_REGION # us-east-2
  PR_NUMBER: ${{ github.event.pull_request.number }}

#   teardown:
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Delete from ECR
#         if: ${{ github.event.pull_request }}
# tag: project-pr#, project-seed-pr#
# - name: Deregister task definition
# if: (synchronize, close)
# - name: Stop ECS Service
# if: (synchronize, close)
# - name: Clear EFS
# if: (synchronize, close)

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      #This step will do six things:
      # 1. set the server image arn environment variable
      # 2. set the seeder image arn environment variable
      # 3. Set Subnet ID environment variable
      # 4. Set Security Group ID Environment Variable
      # 5. Get the Task Execution Role Arn and set it to an environment variable
      # 6. Get the fs-id of our EFS and set it to an environment variable
      - name: set required environment variables

        id: aws-ids
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "IMAGE_ARN=$ECR_REGISTRY/$ECR_REPO:$PROJECT-$PR_NUMBER" >> $GITHUB_ENV
          echo "SEED_IMAGE_ARN=$ECR_REGISTRY/$ECR_REPO:$PROJECT-seed-$PR_NUMBER" >> $GITHUB_ENV

      - name: Build the Application Server
        id: build-server
        uses: ./.github/actions/build-server

      - name: Place the SQL file in EFS
        id: place-sql
        uses: ./.github/actions/seed-db

      - name: Launch the App Service
        id: launch-app
        uses: ./.github/actions/launch-review-app

      - name: "Comment On PR"
        uses: actions/github-script@v3
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }} = context;
            github.issues.createComment({
              issue_number,
              owner,
              repo,
              body: 'Check out the preview here http://${{ env.PUBLIC_URL }}' 
            });
