name: "Teardown Review App"
on:
  pull_request:
    types: [closed]

env:
  ECR_REPO: fleet-ecr
  PROJECT: APP_NAME # request-bin
  SUBNET_ID: DEFAULT_SUBNET_NAME # Fleet-Subnet
  SG_ID: CLUSTER_SECURITY_GROUP # Fleet-Security-3
  TASK_EXECUTION_ROLE_ARN: TASK_EXEC_ROLE_ARN
  FS_ID: EFS_CREATION_TOKEN # FleetFS
  REGION: USER_AWS_REGION # us-east-2
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  teardown:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set ECR Registry Environment Variable
        run: echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Cleanup ECS
        id: cleanup-ecs
        uses: ./.github/actions/cleanup-ecs

      - name: Clear EFS
        id: clear-efs
        uses: ./.github/actions/clear-efs
